-- Table: "TB_BLACKLIST_PERSON_TMP"

-- DROP TABLE "TB_BLACKLIST_PERSON_TMP";

CREATE TABLE "TB_BLACKLIST_PERSON_TMP"
(
  id character varying(20) NOT NULL, -- 人员身份证号
  name character varying(50), -- 人员姓名
  CONSTRAINT "T_BLACKLIST_PERSON_TMP_pkey" PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "TB_BLACKLIST_PERSON_TMP"
  OWNER TO postgres;
COMMENT ON TABLE "TB_BLACKLIST_PERSON_TMP"
  IS '临时黑名单人员表';
COMMENT ON COLUMN "TB_BLACKLIST_PERSON_TMP".id IS '人员身份证号';
COMMENT ON COLUMN "TB_BLACKLIST_PERSON_TMP".name IS '人员姓名';

