-- Table: "TB_BLACKLIST_PERSON_PERMANENT"

-- DROP TABLE "TB_BLACKLIST_PERSON_PERMANENT";

CREATE TABLE "TB_BLACKLIST_PERSON_PERMANENT"
(
  id character varying(20) NOT NULL, -- 主键（人员身份证号码）
  name character varying(50), -- 人员姓名
  description character varying(255), -- 人员上永久黑名单原因
  CONSTRAINT "T_BLACKLIST_PERSON_PERMANENT_pkey" PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "TB_BLACKLIST_PERSON_PERMANENT"
  OWNER TO postgres;
COMMENT ON TABLE "TB_BLACKLIST_PERSON_PERMANENT"
  IS '永久黑名单人员表';
COMMENT ON COLUMN "TB_BLACKLIST_PERSON_PERMANENT".id IS '主键（人员身份证号码）';
COMMENT ON COLUMN "TB_BLACKLIST_PERSON_PERMANENT".name IS '人员姓名';
COMMENT ON COLUMN "TB_BLACKLIST_PERSON_PERMANENT".description IS '人员上永久黑名单原因';

